export const ActionTypes = {
  SET_SEARCH_TYPE: "SET_SEARCH_TYPE",
  SET_POKEMONS: "SET_POKEMONS",
  REMOVE_POKEMONS: "REMOVE_POKEMONS",
  SELECTED_POKEMON: "SELECTED_POKEMON",
  GET_POKEMON_DETAILS: "GET_POKEMON_DETAILS",
  SET_POKEMON_DETAILS: "SET_POKEMON_DETAILS",
  REMOVE_POKEMON_DETAILS: "REMOVE_POKEMON_DETAILS",
};
